### ISSUE TITLE
Support for untrusted destination registry

### ISSUE THREAD

**Issue by dahorak** [arvin-a/openshift-disconnected-operators#1]
It would be good to add option to not verify certificate of the destination registry (add `--tls-verify=false` to `podman push ...` command and `--dest-tls-verify=false` to `skopeo copy ...` command).

**Comment by arvin-a** [comment]
Will add this as an optional flag. In the meantime you can add your registry's cert to the server's trusted ca. The server being where the script is being run from.

**Comment by arvin-a** [comment]
Fixed, forgot to close the bug
